name: Run abaplint via action
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  abaplint-action:
    name: abaplint action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/ci-js-versioning-test@v1-beta1
